### ISSUE TITLE
possibility to make pull requests of this project to the official keyboard?

### ISSUE THREAD

**Issue by kiranos** [JanneEdelman/the-emoji-keyboard#11]
hi is it possible to incorporate this project to jollas own keyboard? Would be great to have this functionality by default

**Comment by JanneEdelman** [comment]
I am not aware of any upstream repository for closed source keyboard components of SailfishOS. I have stated earlier that emoji keyboard layout files are freely available for Mer project, but I won't be active on it. Layout files are also freely available for Jolla to be included into SailfishOS, but I don't have interest to be active on it at the moment when there is no upstream repository.

Above does not apply to font files.
