### ISSUE TITLE
Key layout is missing in 1.0.7.16 after factory reset

### ISSUE THREAD

**Issue by JanneEdelman** [JanneEdelman/the-emoji-keyboard#12]
Jolla upgraded to 1.0.7.16 software and factory reset made after upgrade does not show keyboard layout at all. All subsets are empty like if rendering would crash.

![bp0ocprciaalmy6](https://cloud.githubusercontent.com/assets/6265661/3246775/684b0376-f17e-11e3-9840-6369e8d078ed.png)

Reported by: TMavica@Twitter

**Comment by TMavica** [comment]
I seem figure out whats the problem...this is not your problem.
Should be mine
pls closed this issue

**Comment by JanneEdelman** [comment]
I think this issue has been fixed. At least it can't be reproduced in newer SailfishOS versions.
