### ISSUE TITLE
Possible to get working with android-apps?

### ISSUE THREAD

**Issue by Mortzago** [JanneEdelman/the-emoji-keyboard#13]
The headline says it, is it possible to use this with apps such as Instagram, or is there some unbeatable problem with it? Thank you for your work :)

**Comment by JanneEdelman** [comment]
No, virtual keyboard support in Android Alien Dalvik used in SailfishOS does not support non-16bit Unicode characters. Emoji is mostly outside of 16-bit Unicode range. Currently there is nothing I can do to make this work except to try to get Jolla to fix the issue.
