### ISSUE TITLE
emoj

### ISSUE THREAD

**Issue by jokelap** [JanneEdelman/the-emoji-keyboard#7]
Olen yrittänyt käyttää pelkästään Jollan omaa sms viestiä. Mitakuuluu ohjelmaa en ole vielä kerennyt testaamaan.

**Comment by jokelap** [comment]
Minä olen lähettänyt emoj normaali sms viestinä Jollastani ja toisessa päässä olen yrittänyt vastaan ottaa niitä Nokia 800 omalla sms ohjelmalla.

**Comment by JanneEdelman** [comment]
Duplicate issue / kopio ongelmasta #6
